In [2]:
import numpy as np 
import pandas as pd

In [3]:
data = {
    "Date": pd.date_range("2023-01-01", periods=20),
    "Product": ["A", "B", "C", "D"] * 5,
    "Region": ["East","West", "North", "South", "East", "West", "North", "South", "East", "West", 
               "North", "South", "East", "West", "North", "South","East", "West", "North", "South"],
    "Sales": np.random.randint(100, 1000, 20),
    "Units": np.random.randint(10, 100, 20),
    "Rep": [
        "John", "Mary", "Bob", "Alice", "John", "Mary", "Bob", "Alice", "John", "Mary", 
        "Bob", "Alice", "John", "Mary", "Bob", "Alice", "John", "Mary", "Bob", "Alice"],
}

df = pd.DataFrame(data)

df["Month"] = df["Date"].dt.month_name()
df["Quarter"] = "Q" + df["Date"].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    296     12   John  January      Q1
1  2023-01-02       B   West    569     52   Mary  January      Q1
2  2023-01-03       C  North    664     79    Bob  January      Q1
3  2023-01-04       D  South    877     49  Alice  January      Q1
4  2023-01-05       A   East    592     83   John  January      Q1
5  2023-01-06       B   West    458     89   Mary  January      Q1
6  2023-01-07       C  North    295     20    Bob  January      Q1
7  2023-01-08       D  South    736     90  Alice  January      Q1
8  2023-01-09       A   East    908     76   John  January      Q1
9  2023-01-10       B   West    495     70   Mary  January      Q1
10 2023-01-11       C  North    710     78    Bob  January      Q1
11 2023-01-12       D  South    757     56  Alice  January      Q1
12 2023-01-13       A   East    327     60   John  January      Q1
13 2023-01-14       B   West    564     17   Mary  January      Q1
14 2023-01-15       C  North    177     87    Bob  January      Q1
15 2023-01-16       D  South    608     33  Alice  January      Q1
16 2023-01-17       A   East    529     87   John  January      Q1
17 2023-01-18       B   West    628     70   Mary  January      Q1
18 2023-01-19       C  North    344     69    Bob  January      Q1
19 2023-01-20       D  South    196     80  Alice  January      Q1

In [7]:
pivot1 = pd.pivot_table(df, values='Sales', index='Region',columns='Product', aggfunc='median')
pivot1

Product      A      B      C      D
Region
East     529.0    NaN    NaN    NaN
North      NaN    NaN  344.0    NaN
South      NaN    NaN    NaN  736.0
West       NaN  564.0    NaN    NaN

In [10]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     530.4    NaN    NaN    NaN  63.6   NaN   NaN   NaN
North      NaN    NaN  438.0    NaN   NaN   NaN  66.6   NaN
South      NaN    NaN    NaN  634.8   NaN   NaN   NaN  61.6
West       NaN  542.8    NaN    NaN   NaN  59.6   NaN   NaN

**CROSS TABLE**

In [12]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0